# This Makefile is generated by the made script:
# https://github.com/alx741/made
#
# Replace FILE with your filename
#
# Dependencies:
# 	Pandoc


FILE=entry

all: $(FILE).html $(FILE)_es.html

$(FILE).html: $(FILE).md
	pandoc $< -o $@

$(FILE)_es.html: $(FILE)_es.md
	pandoc $< -o $@

clean:
	rm $(FILE).html
